### ISSUE TITLE
Decide on team members roles (CSS, JS, HTML, Scrum Master, etc)

### ISSUE THREAD

**Issue by TecVector** [DeltaV201n1/FinalProject#3]
As a team member, I need to know who is the best resource for the different elements that this project will require.  

Suggested principal developers:
Scrum Master
JavaScript
HTML
CSS
Architecture

**Comment by ymclapp** [comment]
Suggested principal developers:
Scrum Master - Justin
JavaScript - Justin/Sihem
HTML - Sihem/Yvette
CSS - Yvette/Lilly
Architecture - Justin
